services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=auth_module
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - capstone-network

  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    container_name: web-interface
    ports:
      - "5173:5173"
    volumes:
      - ./web-interface:/app
    depends_on:
      - auth-service
    networks:
      - capstone-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auth_module
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - capstone-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - capstone-network

networks:
  capstone-network:
    driver: bridge

volumes:
  mysql-data:
